### ISSUE TITLE
Implement Parser

### ISSUE THREAD

**Issue by Holmson** [stab-virtual-jabog32/STTR-script#2]
Update Range module to follow new name convention

Wir benötigen nur folgende Funktionen im jeweiligen Gruppen Menü:

From Issue #4

Activate Group
Deactivate Group
ROE Weapons Free
ROE Return Fire
From Issue #7

Clean up module (LATN etc)

**Comment by DTomas15** [comment]
Issue #2 Branch merged into `milestone-initial-test`
