### ISSUE TITLE
ROE function anpassen - Anstatt "return fire" auf "weapons hold"

### ISSUE THREAD

**Issue by Holmson** [stab-virtual-jabog32/STTR-script#9]
Initial ROE State der Gruppen in Editor anpassen: Advanced Waypoint Settings -> ROE = Weapons Hold

Im Script ROE Function anpassen, auf WEAPON_HOLD = 4 anstatt, RETURN_FIRE = 3

**Comment by DTomas15** [comment]
Finde hier etwas widersprüchliche Angaben bzgl der korrekten Nummer. Aber jetzt mal so gemacht.
